export const ActionTypes = {
    GET_LIST_MOVIE: "GET_LIST_MOVIE",
    GET_LIST_MOVIE_BEGIN: "GET_LIST_MOVIE_BEGIN",
    GET_LIST_MOVIE_SUCCESS: "GET_LIST_MOVIE_SUCCESS",
    GET_LIST_MOVIE_ERROR: "GET_LIST_MOVIE_ERROR",
    SHOW_DETAIL_MOVIE: "SHOW_DETAIL_MOVIE",
};
